//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientLourd.DBLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MegaCastingEntities : DbContext
    {
        public MegaCastingEntities()
            : base("name=MegaCastingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Civilite> Civilite { get; set; }
        public virtual DbSet<Contrat> Contrat { get; set; }
        public virtual DbSet<DomaineMetier> DomaineMetier { get; set; }
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<GroupeEmploye> GroupeEmploye { get; set; }
        public virtual DbSet<Internaute> Internaute { get; set; }
        public virtual DbSet<Metier> Metier { get; set; }
        public virtual DbSet<Offre> Offre { get; set; }
        public virtual DbSet<OffresInternaute> OffresInternaute { get; set; }
        public virtual DbSet<Partenaire> Partenaire { get; set; }
        public virtual DbSet<Studio> Studio { get; set; }
        public virtual DbSet<TypeContrat> TypeContrat { get; set; }
    }
}
