//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internaute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Internaute()
        {
            this.OffresInternautes = new HashSet<OffresInternaute>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public System.DateTime date_naissance { get; set; }
        public System.DateTime date_inscription { get; set; }
        public int civilite { get; set; }
        public string lien_google { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string cv_name { get; set; }
        public string email { get; set; }
    
        public virtual Civilite Civilite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffresInternaute> OffresInternautes { get; set; }
    }
}
