//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MegaCastingEntities : DbContext
    {
        public MegaCastingEntities()
            : base("name=MegaCastingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Civilite> Civilites { get; set; }
        public virtual DbSet<Contrat> Contrats { get; set; }
        public virtual DbSet<DomaineMetier> DomaineMetiers { get; set; }
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<GroupeEmploye> GroupeEmployes { get; set; }
        public virtual DbSet<Internaute> Internautes { get; set; }
        public virtual DbSet<Metier> Metiers { get; set; }
        public virtual DbSet<Offre> Offres { get; set; }
        public virtual DbSet<OffresInternaute> OffresInternautes { get; set; }
        public virtual DbSet<Partenaire> Partenaires { get; set; }
        public virtual DbSet<Studio> Studios { get; set; }
        public virtual DbSet<TypeContrat> TypeContrats { get; set; }
    }
}
