//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offre()
        {
            this.Contrats = new HashSet<Contrat>();
            this.OffresInternautes = new HashSet<OffresInternaute>();
        }
    
        public int Id { get; set; }
        public int IdStudio { get; set; }
        public string Intitule { get; set; }
        public int IdMetier { get; set; }
        public System.DateTime DatePublication { get; set; }
        public int DureDiffusion { get; set; }
        public int NombrePostes { get; set; }
        public string DescriptionPoste { get; set; }
        public string DescriptionProfile { get; set; }
        public int IdEmploye { get; set; }
        public string Localisation { get; set; }
        public string CodeOffre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrat> Contrats { get; set; }
        public virtual Employe Employe { get; set; }
        public virtual Metier Metier { get; set; }
        public virtual Studio Studio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffresInternaute> OffresInternautes { get; set; }
    }
}
