//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offre()
        {
            this.OffresInternautes = new HashSet<OffresInternaute>();
        }
    
        public int id { get; set; }
        public int studio { get; set; }
        public string intitule { get; set; }
        public int metier { get; set; }
        public int contrat { get; set; }
        public System.DateTime date_publication { get; set; }
        public int dure_diffusion { get; set; }
        public int nombre_postes { get; set; }
        public string description_poste { get; set; }
        public string description_profile { get; set; }
        public int numero_employe { get; set; }
        public string localisation { get; set; }
    
        public virtual Contrat Contrat { get; set; }
        public virtual Employe Employe { get; set; }
        public virtual Metier Metier { get; set; }
        public virtual Studio Studio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffresInternaute> OffresInternautes { get; set; }
    }
}
