//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCasting.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partenaire
    {
        public int id { get; set; }
        public string siret { get; set; }
        public string adresse { get; set; }
        public int numero_adresse { get; set; }
        public string libelle { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    }
}
